layout_spectrum: 0.9719483
typography_spectrum: 0.5410679
color:
  saturation: 0.2874099
  lightness: 0.6110083
  brandStrength: 0.3003839
  rhythmicContrast: 0.7201749
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Sammy Ortiz
