name: Sammy Ortiz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5410679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080607'
    - '#c63601'
    - '#e97343'
    - '#71828a'
  brandStrength: 0.5
  lightness: 0.6110083
  saturation: 0.2874099
  rhythmicContrast: 0.75
purpose: []
